config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :books
    resources :spells
    
    root to: 'static_pages#home'
    
    #Spells Controller
    get 'spells/:id/add-spell-to-book', to: 'spells#add_spell_to_book', as: 'spell_add_spell_to_book'
    post 'spells/:id/add-spell-to-book', to: 'spells#add_book', as: 'spell_add_book'
  
    #Books Controller
    get 'books/:id/add-spell-to-book', to: 'books#add_spell_to_book', as: 'book_add_spell_to_book'
    post 'books/:id/add-spell-to-book', to: 'books#add_spell', as: 'book_add_spell'
#     post 'books/:id/add-spell-to-book', to: 'books#remove_spell', as: 'book_remove_spell'
#     post 'books/:id', to: 'books#add_spell', as: 'book_add_spell'
    post 'books/:id', to: 'books#remove_spell', as: 'book_remove_spell'

end

app/models/book.rb
class Book < ApplicationRecord
    has_and_belongs_to_many :spells
    
    # Validations
    
    # Name
    validates_presence_of :name
    validates_length_of :name, maximum: 70
    validates_uniqueness_of :name, case_sensitive: false, message: "Cannot be the same as an existing book. Case insensitive."
    
    def self.to_nested_array_for_select
        nested = []
        Book.order(:name).each do |book|
            nested.push [book.name, book.id]
        end
        return nested
    end
    
#     def self.order_by field
#         if field == 'name'
#             return Book.order(:name)
#         elsif field == 'count'
#             return Book.left_outer_joins(:spells).group("books.id").order("count(spells.id)")
#         else
#             return Book.order(:name)
#         end
#     end
    
        #option 1(on Campuswire)
    @@reverse_order_name = false
    @@reverse_order_count = "ASC"
    
    def self.order_by field
        if field == 'name'
            if @@reverse_order_name == false
                @@reverse_order_name = true
                return Book.order(:name)
            else
                @@reverse_order_name = false
                return Book.order(:name).reverse_order
            end
        elsif field == 'count'
            if @@reverse_order_count == "ASC"
                @@reverse_order_count = "DESC"
                return Book.left_outer_joins(:spells).group("books.id").order("count(spells.id) ASC, name ASC")
            else
                @@reverse_order_count = "ASC"
                return Book.left_outer_joins(:spells).group("books.id").order("count(spells.id) DESC, name ASC")
            end
        else
            return Book.left_outer_joins(:spells).group("books.id").order("name ASC, count(spells.id) ASC")
        end
    end
    
#     #option 2 (on Campuswire)
#     @@reverse_order = false
    
#     def self.order_by field
#         if field == 'name'
#             if @@reverse_order == false
#                 @@reverse_order = true
#                 return Book.order(:name)
#             else
#                 @@reverse_order = false
#                 return Book.order(:name).reverse_order
#             end
#         elsif field == 'count'
#             if @@reverse_order == false
#                 @@reverse_order = true
#                 return Book.left_outer_joins(:spells).group("books.id").order("count(spells.id) ASC, name ASC")
#             else
#                 @@reverse_order = false
#                 return Book.left_outer_joins(:spells).group("books.id").order("count(spells.id) DESC, name ASC")
#             end
#         else
#             return Book.left_outer_joins(:spells).group("books.id").order("name ASC, count(spells.id) ASC")
#         end
#     end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /books
  def index
    # We've added a method, self.order_by, to the Book model, 
    # see models/book.rb
    @books = Book.order_by params[:order_by]
  end

  # GET /books/:id
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/:id/edit
  def edit
      @book = Book.find(params[:id])
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = "Successfully added #{@book.name} to All Books."
      redirect_to @book
    else
      render :new
    end
  end

  # PATCH/PUT /books/:id
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to @book
    else
      render :edit
    end
  end

  # DELETE /books/:id
  def destroy
    @book = Book.find(params[:id])  
    if @book.destroy
        flash[:notice] = "Successfully deleted #{@book.name}."
    else
        flash[:notice] = 'Unable to destroy book.'
    end
    redirect_to books_url 
  end
    
  def add_spell_to_book
      @book = Book.find(params[:id])
      @spells = Spell.order_by
  end
    
  def add_spell
      @book = Book.find(params[:id])
      @spell = Spell.find(params[:spell_id])
      if @book.spells << @spell
          if @book.save
             flash[:notice] = "Successfully added #{@spell.name} to #{@book.name}"
          end
      else
          flash[:notice] = "Unable to add spell to book."
      end
      redirect_to @book
  end
    
  def remove_spell
      @book = Book.find(params[:id])
      @spell = Spell.find(params[:spell_id])
      if @book.spells.delete(@spell)
          flash[:notice] = "Successfully removed #{@spell.name} from #{@book.name}."
      else
          flash[:notice] = "Unable to remove spell."
      end
      redirect_to @book
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      # params is a hashtable.  It should have in it a key of :book.
      # The value for the :book key is another hash.
      # If params does not contain the key :book, an exception is raised.  
      # Only the "book" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of :name
      params.require(:book).permit(:name)
#       bp = params.require(:book).permit(:name, :spell_ids => [])
#       bp[:spell_ids] = bp[:spell_ids].reject { |s| s.empty? }
#       return bp
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/books/add_spell_to_book.html.erb
<h1>Add Spell to <%= @book.name %></h1>

<%= link_to "Back to #{@book.name}", book_path %> |
<%= link_to 'Home', root_path %>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Spellname</th>
      <th>School</th>
      <th>Classes</th>
      <th>Concentration</th>
      <th>Add to <%= @book.name %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spells.each do |spell| %>
      <tr>
        <td><%= spell.level %></td>
        <td><%= link_to "#{spell.name}", spell %></td>
        <td><%= spell.school %></td>
        <td><%= spell.spell_classes.to_s %></td>
        <td><%= spell.concentration %></td>
        <td><% if @book.spells.exists?(spell.id) %>
                Already in <%= @book.name %>.
            <% else %>
                <%= form_with(model: @books_spells, local: true, method: 'add_book') do |form| %>
                    <%= form.hidden_field :spell_id, value: spell.id %>
                    <%= form.submit "Add to Book" %>
                <% end %>
            <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<h1>Edit <%= @book.name %></h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Books</h1>

<%= link_to 'Create New Book', new_book_path %> |
<%= link_to 'Home', root_path %>

<br>
<br>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Spell Count', books_path(order_by: 'count') %></th>
      <th><%= link_to 'Name', books_path(order_by: 'name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.spells.count %></td>
        <td><%= link_to "#{book.name}", book %></td>
        <td><%= form_with model: book, local: true, method: 'delete' do |f| %>
                <%= f.submit "Delete Book" %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>Create New Book</h1>

<%= link_to 'All Books', books_path %> |
<%= link_to 'Home', root_path %>
<br>
<br>
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>View <%= @book.name %></h1>

<%= link_to 'All Books', books_path %> |
<%= link_to 'Home', root_path %>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Spellname</th>
      <th>School</th>
      <th>Classes</th>
      <th>Concentration</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book.spells.order_by.each do |spell| %>
      <tr>
        <td><%= spell.level %></td>
        <td><%= link_to "#{spell.name}", spell %></td>
        <td><%= spell.school %></td>
        <td><%= spell.spell_classes %></td>
        <td><%= spell.concentration %></td>
        <td><%= form_with(model: @books_spells, local: true, method: 'remove_spell') do |form| %>
                <%= form.hidden_field :spell_id, value: spell.id %>
                <%= form.submit "Remove Spell" %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Spell', book_add_spell_to_book_path %>