config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :books
    resources :spells
    
    root to: 'static_pages#home'
    
    #Spells Controller
    get 'spells/:id/add-spell-to-book', to: 'spells#add_spell_to_book', as: 'spell_add_spell_to_book'
    post 'spells/:id/add-spell-to-book', to: 'spells#add_book', as: 'spell_add_book'
  
    #Books Controller
    get 'books/:id/add-spell-to-book', to: 'books#add_spell_to_book', as: 'book_add_spell_to_book'
    post 'books/:id/add-spell-to-book', to: 'books#add_spell', as: 'book_add_spell'
#     post 'books/:id/add-spell-to-book', to: 'books#remove_spell', as: 'book_remove_spell'
#     post 'books/:id', to: 'books#add_spell', as: 'book_add_spell'
    post 'books/:id', to: 'books#remove_spell', as: 'book_remove_spell'

end

app/models/spell.rb
class Spell < ApplicationRecord
    has_and_belongs_to_many :books
    
    # Validations
    
    # Name
    validates_presence_of :name, message: ": cannot be blank."
    validates_uniqueness_of :name, case_sensitive: false, message: ": cannot be the same as an existing spell. Case insensitive."
    validates_length_of :name, maximum: 70
    validates :name, uniqueness: true
    
    # Level
    validates_presence_of :level
    validates_numericality_of :level, only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 9
    
    # School
    # Used inclusion, learned from: https://guides.rubyonrails.org/active_record_validations.html#inclusion
    validates_presence_of :school, message: ": cannot be blank."
    school_inclusion_message = ": must be one of the schools listed."
    
    validates :school, inclusion: { in: %w(Conjuration Necromancy Evocation Abjuration
                                            Transmutation Divination Enchantment Illusion), 
                                    message: school_inclusion_message}
    
    # Spell classes
    # Used with_options, learned from: https://api.rubyonrails.org/v6.1.4/classes/Object.html#method-i-with_options
    with_options inclusion: { in: [true, false] } do |spell_class|
    
        spell_class.validates :is_bard
        spell_class.validates :is_cleric
        spell_class.validates :is_druid
        spell_class.validates :is_paladin
        spell_class.validates :is_ranger
        spell_class.validates :is_sorcerer
        spell_class.validates :is_warlock
        spell_class.validates :is_wizard
    end
    
    validate :is_one_or_more_class
    
    def is_one_or_more_class
        if (is_bard.present? == false  && is_cleric.present? == false && is_druid.present? == false && is_paladin.present? == false && 
        is_ranger.present? == false && is_sorcerer.present? == false && is_warlock.present? == false && is_wizard.present? == false)
            errors.add(:spell, ": must have one or more classes.")
        end         
    end
    
    # Concentration
    validates_presence_of :concentration
    validates :concentration, inclusion: { in: %w(Yes No) }
    
    # Description
    validates :description, exclusion: {in: [nil, ""], message: ": cannot be blank."}
    validates_length_of :description, maximum: 4096
    
    #Order spells
    def self.order_by
        return Spell.order(level: :asc, name: :asc)
    end
    
    # Code given in Betterbooks homework instructions, created by instructor/TA
    def self.array_for_select_schools
        array = ["Abjuration", "Conjuration", "Divination", "Enchantment", 
            "Evocation", "Illusion", "Necromancy", "Transmutation"]
        return array
    end
    
    def self.array_for_select_level
        array = [0,1,2,3,4,5,6,7,8,9]
    end
    
    def spell_classes
        spell_classes = Array.new
        if is_bard == true
            spell_classes.push("Bard")
        end
        if is_cleric == true
            spell_classes.push("Cleric")
        end
        if is_druid == true
            spell_classes.push("Druid")
        end
        if is_paladin == true
            spell_classes.push("Paladin")
        end
        if is_ranger == true
            spell_classes.push("Ranger")
        end
        if is_sorcerer == true
            spell_classes.push("Sorcerer")
        end
        if is_warlock == true
            spell_classes.push("Warlock")
        end
        if is_wizard == true
            spell_classes.push("Wizard")
        end
        
        #join elements in an array to produce a string, learned from: https://apidock.com/ruby/Array/join
        string = spell_classes.join(", ")
        return string
    end
    
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /spells
  def index
    @spells = Spell.order_by
  end

  # GET /spells/:id
  def show
      @spell = Spell.find(params[:id])
  end

  # GET /spells/new
  def new
    @spell = Spell.new
  end

  # GET /spells/:id/edit
  def edit
      @spell = Spell.find(params[:id])
  end

  # POST /spells
  def create
    @spell = Spell.new(spell_params)

    if @spell.save
      flash[:notice] = "Successfully added #{@spell.name} to All Spells."
      redirect_to @spell
    else
      render :new
    end
  end

  # PATCH/PUT /spells/:id
  def update
    if @spell.update(spell_params)
      flash[:notice] = "Successfully edited #{@spell.name}"
      redirect_to @spell
    else
      render :edit
    end
  end

  # DELETE /spells/:id
  def destroy
    if @spell.destroy
        flash[:notice] = "Successfully deleted #{@spell.name}"
    else
        flash[:notice] = 'Unable to delete spell.'
    end
    redirect_to spells_url
  end
  
  def add_spell_to_book
      @spell = Spell.find(params[:id])
  end
    
  def add_book
      @spell = Spell.find(params[:id])
      @book = Book.find(params[:book])
      if @spell.books.exists?(@book.id)
          flash[:notice] = "#{@spell.name} already exists in #{@book.name}."
      elsif @spell.books << @book
          if @spell.save
              flash[:notice] = "Successfully added #{@spell.name} to #{@book.name}."
          end
      else   
          flash[:notice] = "Unable to add spell to book."
      end 
      redirect_to spells_url
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def spell_params
      # params is a hashtable.  It should have in it a key of :spell.
      # The value for the :spell key is another hash.
      # If params does not contain the key :spell, an exception is raised.  
      # Only the "spell" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of the following:
      params.require(:spell).permit(:name, :level, :school, :is_bard, :is_cleric, :is_druid, 
          :is_paladin, :is_ranger, :is_sorcerer, :is_warlock, :is_wizard, :concentration, :description)
#       sp = params.require(:spell).permit(:name, :level, :school, :is_bard, :is_cleric, :is_druid, 
#           :is_paladin, :is_ranger, :is_sorcerer, :is_warlock, :is_wizard, :concentration, :description, :book_ids => [])
#       sp[:book_ids] = sp[:book_ids].reject { |b| b.empty? }
#       return sp
    end
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/spells/_form.html.erb
<%= form_with(model: spell) do |form| %>
  <% if spell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spell.errors.count, "error") %> prohibited this spell from being saved:</h2>

      <ul>
        <% spell.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.select :level, Spell.array_for_select_level %>
  </div>

  <div class="field">
    <%= form.label :school %>
    <%= form.select :school, Spell.array_for_select_schools, { prompt: "Select a School" } %>
  </div>

  <div class="field">
    <%= form.label :concentration %>
    <%= form.radio_button :concentration, "No" %>No
    <%= form.radio_button :concentration, "Yes" %>Yes
  </div>

  <div class="field">
    <%= form.label :is_bard? %>
    <%= form.check_box :is_bard %>
  </div>

  <div class="field">
    <%= form.label :is_cleric? %>
    <%= form.check_box :is_cleric %>
  </div>

  <div class="field">
    <%= form.label :is_druid? %>
    <%= form.check_box :is_druid %>
  </div>

  <div class="field">
    <%= form.label :is_paladin? %>
    <%= form.check_box :is_paladin %>
  </div>

  <div class="field">
    <%= form.label :is_ranger? %>
    <%= form.check_box :is_ranger %>
  </div>

  <div class="field">
    <%= form.label :is_sorcerer? %>
    <%= form.check_box :is_sorcerer %>
  </div>

  <div class="field">
    <%= form.label :is_warlock? %>
    <%= form.check_box :is_warlock %>
  </div>

  <div class="field">
    <%= form.label :is_wizard? %>
    <%= form.check_box :is_wizard %>
  </div>
    
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/spells/add_spell_to_book.html.erb
<h1>Add <%= @spell.name %> to Book</h1>

<%= link_to 'All Spells', spells_path %> |
<%= link_to 'Home', root_path %>

<br>
<br>

<%= form_with(model: @books_spells, local: true, method: 'add_book') do |form| %>
    <%= form.label "Select Book:" %>
    <%= form.select :book, Book.to_nested_array_for_select %>
    <%= form.submit "Submit" %>
<% end %>

app/views/spells/edit.html.erb
<h1>Edit <%= @spell.name %></h1>

<%= link_to 'All Spells', spells_path %> |
<%= link_to 'Home', root_path %>
<br>
<br>
<%= render 'form', spell: @spell %>
<br>
<%= form_with model: @spell, local: true, method: 'delete' do |f| %>
        <%= f.submit "Delete Spell" %>
<% end %>

app/views/spells/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>All Spells</h1>

<p>
<%= link_to 'Create New', new_spell_path %> |
<%= link_to "Home", root_path %>    
</p>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Spellname</th>
      <th>School</th>
      <th>Classes</th>
      <th>Concentration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spells.each do |spell| %>
      <tr>
        <td><%= spell.level %></td>
        <td><%= link_to "#{spell.name}", spell %></td>
        <td><%= spell.school %></td>
        <td><%= spell.spell_classes %></td>
        <td><%= spell.concentration %></td>
        <td><%= link_to 'Edit', edit_spell_path(spell) %></td>
        <td><%= link_to 'Add to Book', spell_add_spell_to_book_path(spell) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/spells/new.html.erb
<h1>Create New Spell</h1>

<%= link_to 'All Spells', spells_path %> |
<%= link_to 'Home', root_path %>
<br>
<br>

<%= render 'form', spell: @spell %>

app/views/spells/show.html.erb
<p id="notice"><%= notice %></p>

<h1>View <%= @spell.name %></h1>

<%= link_to 'All Spells', spells_path %> |
<%= link_to 'Home', root_path %>

<p>
  <strong>Level:</strong>
  <%= @spell.level %>
</p>

<p>
  <strong>School:</strong>
  <%= @spell.school %>
</p>

<p>
   <strong>Classes:</strong>
   <%= @spell.spell_classes.to_s %>
</p>

<p>
  <strong>Concentration:</strong>
  <%= @spell.concentration %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spell.description %>
</p>

<%= link_to "Add #{@spell.name} to Book", spell_add_spell_to_book_path %>